version: '2'
services:
  nginx:
    image: nginx
    restart: always
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www
    working_dir: /var/www
    networks:
      main:
        aliases:
          - php.local
  php:
    image: php:7.2-fpm
    command: "php-fpm -dmemory_limit=1024M --allow-to-run-as-root"
    restart: always
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: pass
    volumes:
      - ./php:/var/www
    working_dir: /var/www
    networks:
      - main
networks:
  main:
    driver: bridge
