apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: nginx-php
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-php
    spec:
      containers:
      - name: app
        image: gabrielrcouto/app:1.0
        ports:
        - containerPort: 80
